INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES('John', 'Doe', 'john.doe@example.com');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES('Sam', 'Lee', 'sam.lee@example.com');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES('Tim', 'Johnson', 'tim.johnson@example.com');