-- DROP DATABASE IF EXISTS STUDENT;
-- CREATE DATABASE STUDENT;
-- DROP USER IF EXISTS 'research'@'localhost';
-- CREATE USER 'research'@'localhost' IDENTIFIED BY '12345';
-- GRANT ALL PRIVILEGES ON STUDENT.* TO 'research'@'localhost';


-- DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT(
  ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  FIRST_NAME VARCHAR(64) DEFAULT NULL,
  LAST_NAME VARCHAR(64) DEFAULT NULL,
  EMAIL_ADDRESS VARCHAR(64) DEFAULT NULL,
  SEQ INT DEFAULT 0
);
-- ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;